sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/gitberg.git
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+git://github.com/rdhyee/pg-epubmaker.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WyslCR+bGeejhDcb0ptw/64X/8Y9+4YEQIjLdnZ6AD+UcYPb5XezdvXYLZ7jvNuBWWrx6aJGz4tXJQW2fk07rUxexXxd+vVJJw3n+McEhKADuenyFlKggCh5G1ihW+g2TuLkvkxgUUB9JyPCudEGR0T/NAo/ATj9N9j06LK15RLLBsqCeng5wzlK+E/CV32F+A2RsRLQbd29w5wxQ0TIQTdPyx5z5Gd3c5HGgyqnNqbeagMKpn3+wuMzSBkl3F1qcTa0e/Z49MW+ocZSRZt09Yr74uGAiDBHNw0Mq2406gXsBBvk4bm7JrqWvpi5QIouQEHNDxo0Atmf6jwQlGTNkDnP0TNPL5ZPn03Ur8Tw/gCnkTm5JD6irEQC2Pnmcjkk8WJLNZpEVZOzZ7YW0pG2Ojubt1DV0rCoeh6bajA9XM3In4tdbQ60DdVSiiSszZoFZCyaoS4cjQhQdYPo730uvVUpnNjvtiMUolX0Z0y5DCODXexm6gNd8lKCpkaBESwqaEoKSaWUSTScxqVNGOAm8Ipn14tVrui1UEDhFhE96NBpzcZKczyREZFaS7vyY9BVvofixkZGkMwaaZVMtuyIqxhPRqVlkuMk7bN6ak17iEs1hlphFl6FKbuR5DSregfd8BO+e0uEZjJidk5k54gE5r9fapr3rE7KMzbx7AvISQk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: rdhyee/The-Age-of-Innocence_541
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy